version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
      - /data/maria:/var/lib/mariadb
    ports:
      - "3306:3306"
    #env_file: .env
  testapp:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/testapp
      - ~/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: always
    environment:
      RAILS_ENV: development
    #env_file: .env
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - /data/redis:/var/lib/redis
  mailcatcher:
    image: yappabe/mailcatcher
    restart: always
    ports:
        - 1025:1025
        - 1080:1080